### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by jackolney** [richfitz/rainbowrite#3]
😞 

![screen shot 2017-01-19 at 22 36 24](https://cloud.githubusercontent.com/assets/4134882/22128314/c96adc7c-de97-11e6-88b7-74d44206af63.jpg)

**Comment by richfitz** [comment]
Oh yeah, testthat chafed a while ago and broke everything that used it

**Comment by batpigandme** [comment]
Yeah same prob here 😢
![image](https://user-images.githubusercontent.com/831732/31404145-3e78d1da-adc9-11e7-8446-d60a4a4ab83c.png)

**Comment by richfitz** [comment]
this should be fixed now as I've moved the testthat features out the way

**Comment by jackolney** [comment]
The internet collectively breathes a sigh of relief!
